import type { Metadata } from "next";
import { Roboto_Mono, Lexend } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import logo from '@/assets/LOGO.jpg'
import s from "./style.module.css"

const roboto = Roboto_Mono({
  weight: '300',
  subsets: ['cyrillic'],
})

const lexend = Lexend({
  weight: "400",
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lexend.className} `}
      >
        <header className={s.header}>
          <Image className={s.header_logo} src={logo} alt="LOGO" width={70}/>
          <div className={`${s.header_title} ${roboto.className} `}>
            <p>Erlanbek</p>
            <p>gallary · shop</p>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
